### ISSUE TITLE
emscripten platform not supported

### ISSUE THREAD

**Issue by Fsunroo** [snmishra/ftd2xx#60]
**Description**
using ftd2xx in browser using `py-script` for example is raising Exception of unknown platform in line 23 of ftd2xx.py as the supported platforms are: windows, linux and darwin.
so importing the module in pyscript tag inside a web browser raises error as the platform is emscripten which is not supported. 

**To Reproduce**
html code to reproduce:
```
<!doctype html>
<head>
	<meta charset = 'utf-8'>
	<link rel="stylesheet" href="https://pyscript.net/latest/pyscript.css" />
    <script defer src="https://pyscript.net/latest/pyscript.js"></script>
	<title>TEST</title>
</head>
<body>
	<py-config type="json">
        {
          "packages": ["ftd2xx"]
        }
    </py-config>
	<py-script>
		import sys
		print(sys.platform)
		import ftd2xx
	</py-script>

</body>

```

**Logs**
```
PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 506, in eval_code_async
    await CodeRunner(
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 357, in run_async
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 3, in <module>
  File "/lib/python3.10/site-packages/ftd2xx/__init__.py", line 13, in <module>
    from .ftd2xx import (
  File "/lib/python3.10/site-packages/ftd2xx/ftd2xx.py", line 23, in <module>
    raise Exception("Unknown platform")
Exception: Unknown platform
```

**Desktop (please complete the following information):**
 - OS: error persists on both Linux and windows
 - OS Version: Ubuntu 22.04, Windows 10
 - Python Version: 3.10

**Additional context**
I know it is not actually a bug, but is it even possible to work with usb with the browser???!!

**Comment by snmishra** [comment]
I don't think browser will give access to devices.
